travis:
  secure:
    BINSTAR_TOKEN: jL/uBO76rJD2Dkn8me0lUMTzzidUuw5Zo6w6nZiot2YMM4yDSj13WIIh98qTvqtUmFr09Eeg1MqvndmEr6e0HU3R1/bgHAtVtXRw0ODkF79DPM5npluRq9/5WrswIBjxQ9Q3njzyfijE6Q/1dpm209OtDykzZEIGI6it+cyfCInXqE7Ygqu0Au5j0pRG2XEZ/vaJjc1eVAqRw6AAeCoXrHexXA7Ldj7Ilrp1O75J23TpXpGtH3qWc5BzNAq6gDGYD172BVEANAdhQWi0N7x6p4sJxUtvTqtm57uPsQTGUK3+8SarbrpbxcEzMIQgW5zrRrquf/mvFuR7HAb0BN2Kka5RLNRB1LyPBvTDDyf2tn5ho7lshZsxoZqM3QFXRCBilJCDbdl6Et+dhnCyryRZNX5LE/VLda5UfiK/OOlsEHDXsPxPmzUpAkhYZlq/PgPhwunwDzY+5sGRdUOsTyNL88ioFFcVxCO7deRMkhlKloIRZOXShpnwLuyRldUD5CXgnaYUn6afRX5GBE1HVifg6Y0juXGVo1/xDNj5QpRCNw2prEJhOmIJfwbRBzfrlljfHWR6Z0yHeOuVX29mAkJhwYaGvW9c4LU47CcXYok08dMGXacUwGUe5sEjAkzGojDji2g1kU+Y0X6Sl46t3kUCG1YwF69xshfqszGgnLqn8RQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
