travis:
  secure:
    BINSTAR_TOKEN: HYjfw/b+r6G32eYDs2LJyqAjr7zKnYqEikFlnMWHkOE2vseHEICgA8wm7xR8GmO9TOIgAJpFYEO8zgqmRC1/bpkMT+vtYqy2bTwGbu9c2crRvrXTgJLCQFw5IYZH9aIIh1gUT5bn2U4LMQLUS6RslRxKUWMU0gReet72oXKHfAT7rw7JenLOP3SLyCN2bS5ZOACMtThnRwpsCyRanc+neSINC5oBumSg3hPCLfNgqpH6LqRW8jKjDE9/ck0I5SXmTUiT575wNiyJpt3Qqm6lWkR3p25bEqO5yfybOKWP34luifMS/bm4PBbSg+mrDaDlbH26/AvpZqA1ugr4ztMD/UqRkQNmXzugze6Bjo0V/3g6M1XvqwvxqYjcQuqHE4f2hKRwnTgRtJo1GK2QNXWVgdSLqueqRu1dnFw0u0SAcEgeimICg41I+G5VsS1Wk/0L27mtRFp60GHhxAJVDU6YeSG8gsnyb+6r/GwF4HiIjHfOTJwXO+UlasaHzN07BvxH/7R0cpZncAW58Mnvoa0HVGge3UXVhqwoBtJ2RDv0Gd2X1odOVAyZIaU7JiDybrhqSq2SImTDNlAwN0c2uY/+J8hI0h/UVD2xIfRrjFa2Ze9wIE2YKEAYLzLKuL9OLTY+a7Dvluvoul4VcVY7EiRVcbJ/6Y95TKle7//vEWVePFw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
